version: '3'
services:
  Dev_database:
    image: postgres
    container_name: Breadcrumbs_api_core_development
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Breadcrumbs_api_core_development
    restart: always
