version: '3.9'
services:
  breadcrumbs-api-core-database:
    image: postgres
    environment:
      - POSTGRES_DB=Breadcrumbs_api_core_development
      - POSTGRES_PASSWORD=root
    #ports:
    #  - "5432:5432"
    restart: always
  breadcrumbs-api-core:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - breadcrumbs-api-core-database
